✨ Add login with google
toggl/android pull request #785
Opened 2020-08-24 01:32 UTC by daividssilverio

## Info

### Summary
This PR adds the login with google logic to the welcome reducer.

Why it's a draft: 
- [ ] It's still missing the logic that would fire the `LinkSso` action 
- [ ] It's missing tests

### Technical considerations
I might be forgetting something, but the implementation is looking much simpler with the new apis and kotlin.
If you notice any missing parts, please shout.

### Why is it done like this and not some other way?
🤷 

### Relationships
Closes #663
Closes #664

## Repository health

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

## Reviewing

### Pointers
You may review by commit. But there are not a lot of changes.
To actually see it working, you need to:
- Replace the package name entries on `app/google-services.json.template` from `com.toggl.aurora*` to `com.toggl.giskard*`
- Replace the applicationId to `com.toggl.giskard` on `app/build.gradle`
- Replace some of the secrets in the `app/build.gradle` namely: 
  - `TOGGL_PROJECT_ID`
  - `TOGGL_DROID_GOOGLE_SERVICES_MOBILE_SDK_APP_ID`
  - `TOGGL_DROID_GOOGLE_SERVICES_CLIENT_ID`
  - `TOGGL_DROID_GOOGLE_SERVICES_API_KEY`

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🦑 it after it's not a draft anymore

2020-08-25 14:10 UTC, pdrj commented
As discussed, I'm reviewing this but having trouble making it work locally. I'll continue tomorrow.

2020-08-26 09:27 UTC, pdrj requested changes
I only reviewed code, as said in the comment.

I have some minor suggestions and questions only.

2020-08-26 09:27 UTC, pdrj commented on onboarding/src/main/java/com/toggl/onboarding/welcome/ui/WelcomeFragment.kt
> +            when (ex.statusCode) {
No matter what I do, I get an exception here (error code 10, developer error). 

Having spent a lot of time on trying to get this working, I'll give up for now and only review the code. It'd be great if someone else could give it a quick functional test in the meantime (@heytherewill ?). Alternatively, we can go ahead with just @daividssilverio's tests

2020-08-26 09:27 UTC, pdrj commented on onboarding/src/main/java/com/toggl/onboarding/welcome/ui/WelcomeFragment.kt
> +            val signedInAccount: GoogleSignInAccount = getSignedInAccount() ?: return
Will this let users change the account used for toggl, or will this be as problematic as it is in Xamarin now?

2020-08-26 09:27 UTC, pdrj commented on onboarding/src/main/java/com/toggl/onboarding/welcome/ui/WelcomeFragment.kt
> +        lifecycleScope.launchWhenResumed {
Why is this important to be in resumed state?

2020-08-26 09:27 UTC, pdrj commented on onboarding/src/main/java/com/toggl/onboarding/welcome/ui/WelcomeFragment.kt
> +        runCatching { googleClient.signOut().await() }
The docs for this say: `Signs out the current signed-in user if any. It also clears the account previously selected by the user and a future sign in attempt will require the user pick an account again`

I'd run this everytime (without checking the last signed account) then. Maybe it'll help users switching accounts without needing to clear caches and stuff.

2020-08-27 10:56 UTC, pdrj commented
I finally managed to functionally test this. I'm still totally confused about how it worked for you 😕 I had to add my debug signing key sha to firebase (staging) project. Otherwise I kept getting the exception described somewhere above. Can you do a ./gradlew signingReport and send me the sha1 hash of the key you use on slack? Just out of curiosity.  

Also, my comment:
> I'd run this everytime (without checking the last signed account) then. Maybe it'll help users switching accounts without needing to clear caches and stuff.

might be useless. I'm presented with the account chooser everytime. This might be something device-config specific however (different play versions); so maybe we still want to do the logout each time 🤷

2020-08-27 14:05 UTC, daividssilverio commented on onboarding/src/main/java/com/toggl/onboarding/welcome/ui/WelcomeFragment.kt
> +        withContext(Dispatchers.IO) {
🤔 Not sure if it's really necessary. But it doesn't look like it's gonna hurt to do so.

2020-08-27 14:09 UTC, daividssilverio commented on onboarding/src/main/java/com/toggl/onboarding/welcome/ui/WelcomeFragment.kt
> +            when (ex.statusCode) {
Nice that it worked out in the end. Not sure what I did differently though.

2020-08-27 14:57 UTC, daividssilverio commented on onboarding/src/main/java/com/toggl/onboarding/welcome/ui/WelcomeFragment.kt
> +            val signedInAccount: GoogleSignInAccount = getSignedInAccount() ?: return
It seems to be working quite alright. It logs out the users every time they try to login.

2020-08-27 14:58 UTC, daividssilverio commented on onboarding/src/main/java/com/toggl/onboarding/welcome/ui/WelcomeFragment.kt
> +        lifecycleScope.launchWhenResumed {
I just just did that to avoid firing an intent while the screen isn't visible.

2020-08-27 15:00 UTC, daividssilverio commented on onboarding/src/main/java/com/toggl/onboarding/welcome/ui/WelcomeFragment.kt
> +        runCatching { googleClient.signOut().await() }
The problem is that this call is blocking :/ If there's no account currently signed in, we don't have to make this call at all.

2020-08-28 07:53 UTC, pdrj approved these changes
Works OK.

I made it clearer in #666 that it is that issue's responsibility to take the 'MustAcceptTerms' action further.

2020-08-28 12:26 UTC, merged