🔨 Add, Reduce and Bind LinkSsoButtonTapped action
toggl/android pull request #789
Opened 2020-08-25 19:56 UTC by daividssilverio

## Info

### Summary
This adds, reduces and binds the `LinkSsoButtonTapped` action.

### Technical considerations
The flow to test this action isn't ready yet.
The user needs to go through the login with sso flow to be navigated to the `SsoLinkFragment`.

### Why is it done like this and not some other way?
I think it makes sense to store the e-mail and confirmation code directly in the state, then the `LinkSsoButtonTapped` doesn't need to take in any parameters and can be simply fired when the "log in to enable sso" button is tapped in the `SsoLinkFragment`.

Feel free to make your suggestions.

### Relationships
Closes #658 

## Repository health

### Pull Request checklist

- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

## Reviewing

### Pointers
eh... hard to test without the rest of the flow. But take a look at the tests and the notion page: https://www.notion.so/toggl/SSO-d8929cc996084f3db6fdd08637080f1c.

From my understanding, `MustLinkSsoAccounts` will trigger the navigation to the `SsoLinkFragment` and set the confirmation code to the state.

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🦑 it

2020-08-26 10:55 UTC, pdrj commented
>From my understanding, MustLinkSsoAccounts will trigger the navigation to the SsoLinkFragment and set the confirmation code to the state.

Yeah, that is correct. Mostly, because we don't have the MustLinkSsoAccounts action, as described in my sso effect PR.

2020-08-26 11:22 UTC, pdrj requested changes
Just minor suggestions.

2020-08-26 11:22 UTC, pdrj commented on onboarding/src/main/java/com/toggl/onboarding/common/domain/OnboardingState.kt
> +        internal val confirmationCode: String?,
I actually approached it in a similar way in my sso effect PR. I just have a wrapper over confirmation code and email (we need both of these for linking).

2020-08-26 11:22 UTC, pdrj commented on onboarding/src/main/res/layout/fragment_ssolink.xml
> +        <Button
We could reuse the @style/TextOnboardingButton style and the other button style for the button above

2020-08-26 11:29 UTC, pdrj commented on onboarding/src/main/java/com/toggl/onboarding/common/domain/OnboardingState.kt
> +        internal val confirmationCode: String?,
It seems like we don't need email actually (during the SSO project I vaguely recall it was decided that backend doesn't want that parameter). So your approach without wrapper is OK.

2020-08-27 15:35 UTC, daividssilverio commented on onboarding/src/main/java/com/toggl/onboarding/common/domain/OnboardingState.kt
> +            WelcomeScreenConfiguration.SsoLink,
Oops, yeah.

2020-08-27 15:42 UTC, daividssilverio commented on onboarding/src/main/res/layout/fragment_ssolink.xml
> +        <Button
Alright. I think we'll have to come back to this later though.

2020-08-28 08:19 UTC, pdrj approved these changes
Please apply the small changes before merging. Approving for 🐎

2020-08-28 08:21 UTC, pdrj commented
Hm, the comment about 'small changes' didn't register. Basically, please use the `OnboardingButton` style for the link button (it uses the`Text` one now), the `TextOnboardingButton` for the Cancel button. Then, don't override the width/height and margins if not necessary - this should keep the buttons' dimensions in line with other screens.

2020-08-28 10:55 UTC, daividssilverio commented
@pdrj the cancel button was already like the other usages of "cancel buttons" on onboarding.
I've updated the action button as you requested.

2020-08-28 13:28 UTC, merged