🎇 Process pulled tags and clients
toggl/android pull request #791
Opened 2020-08-26 11:51 UTC by heytherewill

## Info

### Summary
This adds processing of tags and clients

### Technical considerations
Since these are the "simple" entities (as in, they can be created but not edited) I've added them in bundle.

### Why is it done like this and not some other way?
The code is very similar, but I'd rather not have generic methods because it'd make things much more complex (since there's no common interface for entities like in C#)

### Relationships
Please merge after #787 
Closes #744 
Closes #747 

## Repository health

### Pull Request checklist
- [X] The code does not hinder the app's performance
- [X] The code does not introduce regressions
- [X] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

## Reviewing

### Pointers
This is so straightforward that you can just look at the code 

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

## Merge permissions
Anyone, anytime

2020-08-26 12:54 UTC, simonrozsival requested changes

2020-08-26 12:54 UTC, simonrozsival commented on sync/src/main/java/com/toggl/sync/processing/ProcessPulledClients.kt
> +                val localWorkspaceId = syncDao.getWorkspaceIdByServerId(apiClient.workspaceId) ?: continue
The `continue` is kinda scary 🤔 If it ever occurs that we should save a client from a WS that we don't have locally, then there was a major problem that we didn't handle:
- either the server returned other other user's data (the worst case of them all)
- or the server didn't return the workspace itself
- or we deleted the workspace while we shouldn't
- or we messed up the IDs (local vs. server)
- or there's some other problem I can't think of right now.

We should at least log and report that this occurred.

2020-08-26 12:54 UTC, simonrozsival commented on sync/src/main/java/com/toggl/sync/processing/ProcessPulledClients.kt
> +                clientDao.update(updatedWorkspace)
```suggestion
                val updatedClient = apiClient.toDatabaseClient(localWorkspaceId).copy(id = localClient.id)
                clientDao.update(updatedClient)
```

2020-08-26 12:54 UTC, simonrozsival commented on sync/src/main/java/com/toggl/sync/processing/ProcessPulledTags.kt
> +                tagDao.update(updatedWorkspace)
```suggestion
                val updatedTag = apiTag.toDatabaseTag(localWorkspaceId).copy(id = localTag.id)
                tagDao.update(updatedTag)
```

2020-08-26 12:54 UTC, simonrozsival commented on sync/src/main/java/com/toggl/sync/processing/ProcessPulledTags.kt
> +        if (localTag == null) {
Now that I'm looking at this, we might abstract this flow:

```
if (!existsLocally) {
  if (!isServerDeleted) { insert() }
} else {
  if (isServerDeleted) { delete() }
  else { update() }
}
```

... and pass just those three functions/object with those three functions into the generic "decision tree"? It would make the code much simpler and easier to understand.

2020-08-26 12:59 UTC, heytherewill commented on sync/src/main/java/com/toggl/sync/processing/ProcessPulledTags.kt
> +        if (localTag == null) {
I thought about that as well. The problem is that we don't have (and we don't wanna have) a common interface, so the code to actually enable this generic will be really bloated (since different entities need . It's not that much repetition anyways and we'll only touch this code when we add new entities that can be pushed, so we're fine repeating this logic for each of the entities and keeping readability high

2020-08-31 07:25 UTC, heytherewill commented on sync/src/main/java/com/toggl/sync/processing/ProcessPulledClients.kt
> +                val localWorkspaceId = syncDao.getWorkspaceIdByServerId(apiClient.workspaceId) ?: continue
I've created an issue so we can handle this once all entities are being properly pulled: https://github.com/toggl/android/issues/797

2020-08-31 08:54 UTC, simonrozsival approved these changes
LGTM now 👍

2020-08-31 08:54 UTC, merged