🔧 Only show the advanced reports card for non pro workspaces
toggl/android pull request #829
Opened 2020-09-04 19:35 UTC by daividssilverio

## Info

### Summary
This adds the missing part of what had to be done for #578
The layout was already there.

### Technical considerations
🤔 Not sure if we should make an api request like it's being done on #822 for the settings screen.
Should we be using the workspace plans instead of the `isPro` workspace extension?
Calling @dshr and @heytherewill to answer that question.

### Why is it done like this and not some other way?

### Relationships
Closes #578
Maybe depends on #822

## Repository health

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

## Reviewing

### Pointers
None.

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🦑 it after we get a confirmation about the reasonability of the check being made to show the card.

2020-09-07 05:03 UTC, heytherewill requested changes
We were showing to pro users only because we weren't doing the networking to fetch the actual user plan (and detecting a free plan can be done offline). With the code added in the other PR, we can easily how this screen to everyone, so closing the linked issue is just a matter of navigating to the correct route and adding tests

2020-09-10 14:11 UTC, daividssilverio commented
So, the workspace plan view currently works with the default workspace id from the user and there's no UI to change your workspace for visualization purposes only in said view.

@heytherewill  Should we make some adhoc adaptations directly on this PR? Or is it better to create some issues to handle it?

I think we would need to:
- Make the route `Route.WorkspacePlan` accept a parameter.
- Make the Settings state hold the `currently selected workspace` for the workspace plan view.
- Clean up the `currently selected workspace` when leaving the workspace plan view.
- Add some loading state in the workspace plan view...
- Change how we fire the workspace plan loading effect (I think we can fire it when the workspace plan view appears) instead of when the default workspace changes.

2020-09-10 14:18 UTC, daividssilverio commented
For now, I'm using the `isPro` offline extension and navigating to the workspace plan view as it currently works.

2020-09-16 06:22 UTC, heytherewill commented on reports/src/main/java/com/toggl/reports/domain/ReportsReducer.kt
> +                if (selectedWorkspaceId == null) noEffect()
If the user has not yet selected a workspaceId, we default to showing data of the default workspaceId (be it the user's default workspaceId or the first workspaceId when that is null). Why not do the same here?

2020-09-16 18:26 UTC, daividssilverio commented on reports/src/main/java/com/toggl/reports/domain/ReportsReducer.kt
> +                if (selectedWorkspaceId == null) noEffect()
Good catch. As it is, if the user never selected a workspace and saw the `AvailableOnOtherPlans` card, it would be unresponsive.

2020-09-21 19:04 UTC, heytherewill approved these changes

2020-09-21 19:33 UTC, merged