🐛 Fix user initial default workspace id setup
toggl/android pull request #830
Opened 2020-09-05 01:28 UTC by daividssilverio

## Info

### Summary
This fixes the initial user setup.
We were setting the user received from the api into the state with outdated data. 
The database was setup with the correct default local workspace id, but the state was set with default server workspace id.

### Technical considerations
None.

### Why is it done like this and not some other way?
I just renamed the the `set` method to `setAndConfigureDefaultWorkspace` to be more explicit.
But we could also have gone like this in all effects:
```
userRepository.set(user)
updatedUser = userRepository.get()
```

What do you think?

### Relationships
Closes #642

## Repository health

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

## Reviewing

### Pointers
Test it out.

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🦑 it

2020-09-07 05:01 UTC, heytherewill requested changes
Do add tests to prevent us from making this mistake again

2020-09-07 13:31 UTC, pdrj approved these changes
👍

It'd be nice to have tests, as Will said.

2020-09-08 18:00 UTC, daividssilverio commented
I've also added the missing test for the sign up with 3rd party effect.

2020-09-08 18:30 UTC, heytherewill approved these changes

2020-09-08 19:30 UTC, merged