✨ Improve progress and exception handling
toggl/android pull request #842
Opened 2020-09-10 15:43 UTC by semanticer

## Info

### Summary
This PR implements basic exception handling in sync sequence. It also improves the debug listener and adds progress reporting listener.

### Technical considerations
This is not a complete equivalent of [xamarin code](https://github.com/toggl/mobileapp/blob/54bb2f1194b97fac59113222caaf390a4acf1581/Toggl.Core/Sync/SyncManager.cs#L166) yet, some of the exceptions from Xamarin are not even defined in Aurora so I'm not sure if we should create some further issues to take care of this or...? 🤷 

### Relationships

Closes #772 - kinda

## Repository health

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

## Reviewing

### Pointers
You can check the log if everything is reported correctly, you can also try `syncLauncher.enqueueSync().observe( ... )` to verify you are getting some progress data back. 

And you can also try throwing some exception in one of the sync steps and verify it has been caught correctly.

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🦑

2020-09-10 19:39 UTC, heytherewill requested changes

2020-09-10 19:39 UTC, heytherewill commented on sync/src/main/java/com/toggl/sync/SyncLauncher.kt
> +    fun enqueueSync(): LiveData<WorkInfo?>? {
Please expose a Flow

2020-09-10 19:39 UTC, heytherewill commented on sync/src/main/java/com/toggl/sync/SyncWorker.kt
> +        SyncDebugListener(syncSequence.stepCount) { msg -> setForeground(createForegroundInfo(msg)) }
Why not inject all of these using `@Binds @IntoSet`?

2020-09-10 19:39 UTC, heytherewill commented on sync/src/main/java/com/toggl/sync/SyncWorker.kt
> +            .setSmallIcon(android.R.drawable.ic_popup_reminder) // TODO we need a better icon
Please ping designers or create an issue!

2020-09-11 10:32 UTC, semanticer commented on sync/src/main/java/com/toggl/sync/SyncWorker.kt
> +            .setSmallIcon(android.R.drawable.ic_popup_reminder) // TODO we need a better icon
https://github.com/toggl/android/issues/844

2020-09-15 13:41 UTC, semanticer commented on sync/src/main/java/com/toggl/sync/sequence/SyncSequence.kt
> +typealias SyncSequenceListenerProvider = (ProgressReporter) -> SyncSequenceListener
I am sooooo Kotlin 1.3

2020-09-15 14:50 UTC, simonrozsival commented
> This is not a complete equivalent of xamarin code yet, some of the exceptions from Xamarin are not even defined in Aurora so I'm not sure if we should create some further issues to take care of this or...? 🤷

I guess this PR doesn't close #772 - we really need to handle all those cases (`NoDefaultWorkspaceException`, `ClientDeprecatedException`, `ApiDeprecatedException` (teapoting), `UnauthorizedException` (API token was reset - soft logout)). I think you can merge this PR as long as the issue #772 stays open.

2020-09-22 06:31 UTC, simonrozsival approved these changes
All the exceptions are there now 👍

2020-09-24 04:29 UTC, heytherewill approved these changes
Looks great! One thing that I want you to change: Please change the `SyncStep` enum that is currently part of the AppState into the nicer `SyncProgress` sealed class for consistency 💪 

I'm approving for :sanic: though

2020-09-24 11:55 UTC, merged