🔨 Add the remaining feedback data
toggl/android pull request #843
Opened 2020-09-11 00:45 UTC by daividssilverio

## Info

### Summary
This PR adds the remaining data needed to compose the feedback data.
DRAFT:
- [ ] Missing tests
- [ ] The user timezone is still missing

### Technical considerations
I've used yet another common reducer for the `*SetUser` onboarding actions... I'm not a fan... but I'm not sure of a better way to do it.

### Why is it done like this and not some other way?
Suggestions to improve it are always welcome.

### Relationships
Closes #579

## Repository health

### Pull Request checklist

- [ ] The code does not hinder the app's performance
- [ ] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

## Reviewing

### Pointers

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🦑 after the draft is done

2020-09-11 05:22 UTC, heytherewill requested changes

2020-09-11 05:22 UTC, heytherewill commented on common-android/src/main/java/com/toggl/common/storage/LastTimeUsageStore.kt
> +private const val lastLoginKey = "lastSyncAttemptKey"
©️ 🍝

2020-09-11 05:22 UTC, heytherewill commented on common-feature/src/main/java/com/toggl/common/feature/di/CommonFeatureModule.kt
> +@Module(includes = [ApiModule::class])
Is this at all needed now with Hilt?

2020-09-11 05:22 UTC, heytherewill commented on common-feature/src/main/java/com/toggl/common/feature/di/CommonFeatureModule.kt
> +        LastTimeUsageStore(sharedPreferences, timeService)
You don't need a `Provides` method since you are not injecting an interface

2020-09-11 05:22 UTC, heytherewill commented on onboarding/src/main/java/com/toggl/onboarding/common/domain/UserSetCommonReducer.kt
> +            action.isOrWraps<SsoAction.SetUser>()
You could also make there actions implement a common interface 🤔

2020-09-11 05:22 UTC, heytherewill commented on onboarding/src/main/java/com/toggl/onboarding/common/domain/UserSetCommonReducer.kt
> +            action.isOrWraps<SsoAction.SetUser>()
I'd rename this reducer to `AuthenticationSucceededReducer` as well

2020-09-11 13:35 UTC, daividssilverio commented on common-feature/src/main/java/com/toggl/common/feature/di/CommonFeatureModule.kt
> +@Module(includes = [ApiModule::class])
Turns out we don't need it. (Well, it built, it didn't crash).

2020-09-15 06:25 UTC, heytherewill approved these changes
Looking good now, but please fix the DI

2020-09-15 06:25 UTC, heytherewill commented on common-feature/src/main/java/com/toggl/common/feature/di/CommonFeatureModule.kt
>  }
Oh, my point was that you don't need this method *at all*. You can just 🔥 this whole thing.

2020-09-15 06:25 UTC, heytherewill commented on common-android/src/main/java/com/toggl/common/storage/LastTimeUsageStore.kt
> +
Just add `@Singleton` here and delete the method from the module ✨

2020-09-15 14:22 UTC, merged