🔄 Process push results
toggl/android pull request #845
Opened 2020-09-11 12:23 UTC by pdrj

## Info

### Summary
Adds processing of the push results

### Technical considerations
This is a WIP since I lack the knowledge of how sync server is supposed to work and what can I expect there to be in the response. There are some casts that might not be safe, so I'll need someone more familiar with this stuff to tell me if I'm going the right way here.

I've tried to trigger an actual response from the server, but the best I can do is either to get a SyncError back, or a bad request 😄. I couldn't test it properly then.

It only covers workspaces for now, to get some validation that I'm doing the right thing.

### Why is it done like this and not some other way?

### Relationships

Closes #779 

## Repository health

### Pull Request checklist

- [ ] The code does not hinder the app's performance
- [ ] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

## Reviewing

### Pointers

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
Anyone

2020-09-14 15:12 UTC, simonrozsival requested changes

2020-09-14 15:12 UTC, simonrozsival commented on sync/src/main/java/com/toggl/sync/processing/ProcessPushedWorkspaces.kt
> +        }
This is kinda cryptic. I had to think for a while what's going on here. Let's move the logic into a separate function please (`if (doesNotExistLocally(action) continue`). Also should it really be a `return` and not a `continue`? 🤔

2020-09-14 15:12 UTC, simonrozsival commented on sync/src/main/java/com/toggl/sync/processing/ProcessPushedWorkspaces.kt
> +        val localId = apiWorkspace.meta?.clientAssignedId?.id ?: return
I think that this is wrong. If this was an `update` or `delete` action, you would have to find the `localId` using the server ID (`apiWorkspace.meta.id`). Here you would skip the results of all `delete` and `update` actions where `clientAssignedId` is not present in the response (the `MetaInfo` class is a "union" of all possible forms of the `"meta"` object values, it's a bit confusing..)

2020-09-14 15:12 UTC, simonrozsival commented on sync/src/main/java/com/toggl/sync/processing/ProcessPushedWorkspaces.kt
> +    for (apiWorkspace in workspaces) {
I'd prefer if this was `actionResult` instead of `apiWorkspace`. The workspace itself should be in the `payload.result` for the `create` action results.

2020-09-14 15:12 UTC, simonrozsival commented on sync/src/main/java/com/toggl/sync/processing/ProcessPushedWorkspaces.kt
> +                            (result.id as Some).value,
This looks dangerous 👀

2020-09-14 15:12 UTC, simonrozsival commented on api/src/main/java/com/toggl/api/network/models/sync/PushResponse.kt
> +    val preferences: ActionResult<SyncApiPreferences>?
I think that this should actually contain `PushActionResult<ApiTimeEntry>` and not the `SyncApiTimeEntry` with the optional properties (which are intended for partial serialization of the push request body). The same would apply for the rest of the entity types, it's not just TEs. We wouldn't have to do the weird `(result.id as Some).value` cast to get the deserialized value.

2020-09-14 15:12 UTC, simonrozsival commented on sync/src/main/java/com/toggl/sync/processing/ProcessPushedWorkspaces.kt
> +                        DatabaseWorkspaceWithoutFeatures(
This could be extracted into an extension function.

2020-09-14 15:12 UTC, simonrozsival commented on database/src/main/java/com/toggl/database/dao/SyncDao.kt
> +    abstract suspend fun setSynced(
This should be either called `setWorkspaceSynced` or something like that, or it should be in the `WorkspaceDao`

2020-09-16 07:30 UTC, simonrozsival commented on sync/src/main/java/com/toggl/sync/processing/ProcessPushedWorkspaces.kt
> +            is ActionResult.EntitySuccessResult -> {
You're missing one more case here - `ActionResult.SuccessResult` - which is what you expect to get for successful `Update` and `Delete` actions (which have no payload when processing was successful).

2020-09-18 17:58 UTC, simonrozsival commented
@pdrj I made quite a few changes and I believe the implementation is almost complete but we still need to add a bunch of unit tests. I will work on that on Monday.

2020-09-18 18:29 UTC, simonrozsival commented
We should consider merging `PushSyncDao<T>` (which I added) and `EntityDao<T>` which was added by a different PR.

2020-09-22 06:38 UTC, heytherewill approved these changes

2020-09-22 08:56 UTC, semanticer approved these changes
I had the whole list of suggestions ready to throw at you when I realized that I'm looking at the old version of this PR and you had already made all the changes I wanted to suggest.  🤷

2020-09-22 09:58 UTC, pdrj reviewed
I can't approve it, as I created it, but since pretty much all my WIP stuff is gone, I gave it a test and it is looking good 👍

2020-09-22 12:09 UTC, simonrozsival approved these changes

2020-09-22 12:12 UTC, merged