Time entries log overhaul
toggl/android pull request #907
Opened 2020-09-23 07:03 UTC by heytherewill

## Info

### Summary
This PR applies that very welcome coat of paint in the time entries log so that they are aligned with our current designs!

### Technical considerations
I needed to add a property yo check whether a time entry is part of a group of not. That was really easy to do thanks to our architecture!
The state handling doesn't look as nice, but that's because I'm biased towards Compose; with a compose state of mind, every view holder will look disgusting

Also, you'll notice that for the suggestion/time entry cards I'm not using the card background, but painting the ConstraintLayout instead. This is to prevent material design from changing the color of the cards when in dark mode while keeping the shadow in light mode (that's the default way of applying elevation in dark mode)

STILL MISSING:

- [ ] Show cards in collapsed entry groups
- [ ] Underline the selected tab
- [ ] Display the sync state in time entries
- [ ] Display the duration of the running time entry properly
- [ ] Fixing tests on the places where I had to change the selector

### Relationships
Closes #862
Closes #886
Closes #892

## Repository health

### Pull Request checklist
- [X] The code does not hinder the app's performance
- [X] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

## Reviewing

### Pointers
The commits won't be that helpful since a lot of the changes are cosmetic. Instead, check the bits that have some domain logic and ensure those are correct. Then, check the ViewHolders to see if there are any crimes against humanity there. If all that is well, do a proper functional test while looking at the final designs. I recommend testing using a proper account with actual data.

The review template below is actually quite useful and I recommend using it. Ah: And don't forget dark mode :sogood:

### Review template
- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones
- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions

2020-09-24 14:21 UTC, pdrj reviewed
![Screenshot 2020-09-24 at 16 20 10](https://user-images.githubusercontent.com/53510080/94157780-e423a900-fe81-11ea-8beb-a63eb1ab6106.png)

I've only just started reviewing this and noticed that we don't have the billable/project icons shown on the running tab like here https://toggl.invisionapp.com/console/%5BAndroid%5D-Rebranding-ckem8stapzb0o01wrr0c27nd1/ckeriu1sh02aw01xk3ziubmky/play#project_console

Also, the running tab is pinkish instead of white. 

I'll continue with the feedback tomorrow. :)

2020-09-25 08:45 UTC, pdrj requested changes
Visual comments:

1. The dot is not aligned with text ![Screenshot 2020-09-25 at 10 10 02](https://user-images.githubusercontent.com/53510080/94243286-79bd4800-ff17-11ea-93ca-2495d0d7a2d4.png)
2. The bottom bar is expanding with long descriptions
![Screenshot 2020-09-25 at 10 15 25](https://user-images.githubusercontent.com/53510080/94243703-0ec04100-ff18-11ea-990c-9171d946b968.png)
3. Suggestions header says 'Track again' in designs.
4. The 'Play icon' has sharp edges in the designs, we have sort of soft edges
5. 'Im working on' background is white in designs.
6. Description of TEs is in bold in designs
7. In dark mode, the settings icon is white in designs.
8. (From my previous comment) Background of running TE in light mode 
9. 8. (From my previous comment) Billable/project icons on running TE
10. Spacings are inconsistent in the designs, but do you think we should add just a little more room between TE description and project lines in log items?

2020-09-25 09:09 UTC, pdrj requested changes
Functional test:

1. Can't edit singular TEs (can edit groups only, but not singular items in an expanded group)
2. Can't do swipe actions over groups (can swipe over singular TEs only). Can't do swipe actions over items of an expanded group either.
3. Leakcanary is reporting a leak of RunningTimeEntryFragment instance (via updateDurationTickJob) - the job is not cancelled I think.

2020-09-25 10:50 UTC, pdrj submitted a review, later dismissed
Lots of good stuff in here. Really digging the expand/collapse animations and haptic feedback 👍 

I've mostly cosmetic comments.

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/log/ui/TimeEntryItemViewHolder.kt
> +    private val oneDpElevation = itemView.context.resources.getDimension(R.dimen.base_elevation)
We can DRY it up a bit by moving `oneDpElevation` to the parent.

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/running/ui/RunningTimeEntryFragment.kt
> +            .launchIn(lifecycleScope)
Let's use `viewLifecycleOwner.lifecycleScope` to be safe.

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/res/layout/fragment_running_time_entry.xml
> +        android:layout_height="24dp" />
Let's extract every hardcoded dimen (that makes sense to be reused) in this file.

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/res/layout/fragment_running_time_entry.xml
> +        android:fontFamily="sans-serif-medium"
Probably out of scope of this PR, but we're redefining these text styles all over timer module. Would be nice to have a style.

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/res/layout/fragment_time_entries_log.xml
> +            android:paddingBottom="120dp"
Where did the `120` come from? Should it be a dimen dependent on some other dimens?

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/res/layout/time_entries_log_header.xml
> +    android:layout_height="36dp"
Again would be nice to not have hardcoded `dps`

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/res/layout/time_entries_log_suggestion.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Please run a reformat on this file so we start in a clean state.

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/res/layout/time_entries_log_suggestion.xml
> +            android:layout_width="48dp" />
Again, let's extract `dimens` that make sense.

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/log/domain/TimeEntriesLogSelector.kt
> +                                val groupSize = if (groupIsExpanded) timeEntryGroup.size else min(timeEntryGroup.size, 3)
Let's name the constant, it is quite invisible hardcoded like that ;)

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/log/ui/SwipeActionCallback.kt
> +            is TimeEntryGroupViewHolder -> ItemTouchHelper.LEFT.or(ItemTouchHelper.RIGHT)
It reads nicer to me in full infix style (here and elsewhere in this file)
```suggestion
            is TimeEntryGroupViewHolder -> ItemTouchHelper.LEFT or ItemTouchHelper.RIGHT
```

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/log/ui/TimeEntryContentViewHolder.kt
> +        if (formattedProjectText.isNotBlank()) {
For projects, here and elsewhere I'd consider checking for null only. I can imagine someone wanting to only have a colored dot displayed, without any text and identify projects just by color 🤔

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/log/ui/TimeEntryItemViewHolder.kt
> +        durationGradient.background = ContextCompat.getDrawable(
Let's reuse all the drawables created on each bind (have just one instance of each).

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/suggestions/ui/SuggestionsAdapter.kt
> +        if (formattedProjectText.isNotBlank()) {
Same comment as somewhere above about project name blank vs null.

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/res/layout/fragment_running_time_entry.xml
> +        android:layout_width="24dp"
Please reformat so attributes are in correct order.

2020-09-25 10:50 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/running/ui/RunningTimeEntryFragment.kt
> +        timeIndicatorTimer?.cancel()
This should be also cancelled when the view gets destroyed.

2020-09-28 07:38 UTC, heytherewill commented on timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogAdapter.kt
> +        const val timeEntryInClosedGroupViewType = 109
The problem here is that we have two different view types that map to the same holder. We need to reuse the holder in order to have proper animations, but we need two different view types in order to identify which views are visible and which are not in the ViewDecorator. That's why I went with prime numbers instead

2020-09-28 07:43 UTC, heytherewill commented on timer/src/main/res/layout/fragment_running_time_entry.xml
> +        android:fontFamily="sans-serif-medium"
I'd rather focus our efforts on properly extracting Composable functions rather than extracting XML

2020-09-28 07:46 UTC, heytherewill commented on timer/src/main/java/com/toggl/timer/log/ui/TimeEntryContentViewHolder.kt
> +        if (formattedProjectText.isNotBlank()) {
Nice thinking!

2020-09-28 08:06 UTC, heytherewill commented on timer/src/main/res/layout/time_entries_log_suggestion.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Turns out our editor config and our `spotlessApply` have many differences 🤔 We should consider improving spotless in another PR

2020-09-28 08:25 UTC, heytherewill commented on timer/src/main/java/com/toggl/timer/log/ui/TimeEntryItemViewHolder.kt
> +        durationGradient.background = ContextCompat.getDrawable(
How would you go about doing that while preventing them from leaking?

2020-09-28 08:36 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/log/ui/TimeEntryItemViewHolder.kt
> +        durationGradient.background = ContextCompat.getDrawable(
Would having it stored as a field cause a leak? I don't think it holds the context reference, it just uses it to access resources. 🤔

2020-09-28 11:31 UTC, pdrj requested changes
Just some minor comments and questions left.

Two things that need fixing that I've noticed:

- a bit of an edge case, but it'd be nice to have a bit more spacing ![Screenshot 2020-09-28 at 13 03 22](https://user-images.githubusercontent.com/53510080/94427052-cb233c80-018e-11eb-9259-5497d9afcd88.png)
- swipe actions don't work over groups

2020-09-28 11:31 UTC, pdrj commented on timer/src/main/res/layout/time_entries_log_suggestion.xml
> +            android:layout_height="24dp"
We can use the arrow size constant here too.

2020-09-28 11:31 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/running/ui/RunningTimeEntryFragment.kt
> +            .launchIn(lifecycleScope)
Why have you decided to keep `lifecycleScope`? Do you think it's safe in this case? 🤔

2020-09-28 11:31 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/log/ui/OverlappingCardDecorator.kt
> +            outRect.set(0, 0, 0, 0)
In the name of dry, it should be safe to just do it once at the top instead before each return.

2020-09-28 11:32 UTC, pdrj commented on timer/src/main/java/com/toggl/timer/running/ui/RunningTimeEntryFragment.kt
> +            .launchIn(lifecycleScope)
Unresolving so you see this :)

2020-09-28 13:30 UTC, pdrj requested changes
One more thing I just noticed is that we use black for the TE titles and stuff, while the designs use our purple. It should be OK to change this app-wide (it is, modify the text_on_{primary,surface}).

2020-09-28 14:55 UTC, daividssilverio commented
It looks like the running time entry card has the wrong shape, it has squared borders inside a rounded shape.
![image](https://user-images.githubusercontent.com/2173493/94448355-cb184200-0178-11eb-85d9-d46e1987905c.png)

2020-09-28 19:38 UTC, daividssilverio requested changes
Looking good! I left a few comments.
Also, the time entry log items in this PR are using this purple, and the designs are using only the `#161119`.
![image](https://user-images.githubusercontent.com/2173493/94477224-95d31a80-019f-11eb-883f-3140e9e7a0b8.png)

I like the purple, but I think we need to discuss this with the designers. Also, neither is working well in dark mode. Really hard to see the grouped time entries.
![image](https://user-images.githubusercontent.com/2173493/94477621-27db2300-01a0-11eb-8e76-568934e5c42f.png)

2020-09-28 19:50 UTC, daividssilverio commented
We are still missing the current page indicator in the `BottomNavigationView`:
![image](https://user-images.githubusercontent.com/2173493/94478487-560d3280-01a1-11eb-8014-d2a3cc9401ff.png)

I don't think the bottom navigation view supports that out of the box, so it's fine to create an issue for that if you'd prefer. I think we could use a pager or a pager strip or a custom view for that.

Also, the icon colours don't match the designs in both light/dark modes.

2020-09-28 20:05 UTC, daividssilverio commented on timer/src/main/java/com/toggl/timer/log/ui/OverlappingCardDecorator.kt
> +    private val percentageOfVisibleCardAfterOffsetting = 100 / 5F
This name is misleading. I've tried changing it the higher the value and this doesn't seem to work like a %.
For example, setting this value to 2 looks like this:
![image](https://user-images.githubusercontent.com/2173493/94480317-1dbb2380-01a4-11eb-821a-b5fb534b33f8.png)
Setting it to 25 looks like this:
![image](https://user-images.githubusercontent.com/2173493/94480351-30cdf380-01a4-11eb-8c67-7454456688c4.png)

Another point, the visible offset in the designs are even smaller than the example above.
It looks like this:
![image](https://user-images.githubusercontent.com/2173493/94480481-5e1aa180-01a4-11eb-85d3-06f23e2e1b41.png)

2020-09-28 20:07 UTC, daividssilverio commented
Are you implementing the grouped time entries designs in this PR? They don't have the item separation in the designs.
https://toggl.invisionapp.com/console/%5BAndroid%5D-Rebranding-ckem8stapzb0o01wrr0c27nd1/ckeriu1sh02av01xk0y9b4m7z/inspect

2020-09-29 13:27 UTC, heytherewill commented
@pdrj We're actually no using black; We are using the correct shade of dark purple for text, as per designs 🤔

2020-09-29 13:30 UTC, pdrj commented
> @pdrj We're actually no using black; We are using the correct shade of dark purple for text, as per designs 🤔

My bad then, hard to tell them apart 😄

2020-09-29 13:51 UTC, heytherewill commented on timer/src/main/java/com/toggl/timer/running/ui/RunningTimeEntryFragment.kt
> +            append(clientName)
Let's create a followup issue, then

2020-09-29 16:40 UTC, daividssilverio commented on timer/src/main/java/com/toggl/timer/log/ui/SwipeActionCallback.kt
> +            clipRect(backgroundBounds)
Is this doing anything?

2020-09-29 16:53 UTC, daividssilverio commented on timer/src/main/java/com/toggl/timer/log/ui/OverlappingCardDecorator.kt
> +    private val visibleCardHeightAfterOffsetting = cardHeight / (100 / percentageOfVisibleCardAfterOffsetting)
`percentageOfVisibleCardAfterOffsetting` now is not doing anything, right?

2020-09-29 17:12 UTC, daividssilverio commented
Not sure if this is a problem or a feature, but since we are not moving the grouped time entries when the group header is swiped, we have this effect.
![image](https://user-images.githubusercontent.com/2173493/94589553-6382f500-0253-11eb-9a35-adddc751780b.png)

I've also noticed that the swipe action's text paint could use a anti alias flag.

2020-09-29 17:16 UTC, daividssilverio commented on timer/src/main/java/com/toggl/timer/log/ui/TimeEntryItemViewHolder.kt
> +        itemView.isClickable = false
actually, this has to happen after the `itemView.setOnClickListener(null)` call, it internally sets `isClickable` to true, whether or not the listener is null.

2020-09-29 17:21 UTC, daividssilverio commented on timer/src/main/res/layout/fragment_time_entries_log.xml
> +        app:elevation="@dimen/plane_02"
Hey, using `cardElevation` provides a nicer effect here. Also, We might consider putting this on a higher plane.

2020-09-29 17:26 UTC, daividssilverio commented on timer/src/main/res/layout/fragment_running_time_entry.xml
> +        android:background="@drawable/gradient_transparent_to_running_entry_card"
The gradient isn't right here: 
![image](https://user-images.githubusercontent.com/2173493/94593415-43553500-0257-11eb-9f90-adc56dc9b851.png)

2020-09-29 17:37 UTC, daividssilverio reviewed
Looking good! Please create issues for the layout details and colours not handled here.
- The bg colour of the time entries
- The tab indicator in the bottom nav
- The layout of the grouped time entries
- ?? The grouped time entries swiping (not sure if we are doing, but it would be a nice detail to swipe the whole group) ¿¿

2020-09-30 05:20 UTC, heytherewill commented on timer/src/main/java/com/toggl/timer/log/ui/SwipeActionCallback.kt
> +            clipRect(backgroundBounds)
Nope

2020-09-30 05:21 UTC, heytherewill commented on timer/src/main/java/com/toggl/timer/log/ui/OverlappingCardDecorator.kt
> +    private val visibleCardHeightAfterOffsetting = cardHeight / (100 / percentageOfVisibleCardAfterOffsetting)
Not when the percentage is 1, but it makes it easier to understand and change the amount of visible card in the future so I think it's worth keeping it

2020-09-30 05:24 UTC, heytherewill commented on timer/src/main/res/layout/fragment_time_entries_log.xml
> +        app:elevation="@dimen/plane_02"
The problem of card elevation is the fact that our designs didn't consider the automatic elevation added by the material design library to dark theme surfaces

2020-09-30 05:31 UTC, heytherewill commented
> The bg colour of the time entries

There's nothing wrong here, I'm using the exact same color as the one in designs, what do you mean? 🤔 

> The tab indicator in the bottom nav

I will give one final try here and create an issue otherwise 👌 

> The layout of the grouped time entries

I'm also not sure what you mean here D:

> The grouped time entries swiping (not sure if we are doing, but it would be a nice detail to swipe the whole group) ¿¿

We won't change them to swipe altogether until we are doing compose where this is much easier

2020-09-30 11:20 UTC, pdrj approved these changes
Looking good!

Minor points that I noticed, but not blocking:
- the drawable reusing I suggested in a previous conversation
- the swipe overlay over groups looks like it's too small, but we can live with that ;)

2020-09-30 12:27 UTC, daividssilverio commented
>> The bg colour of the time entries

>There's nothing wrong here, I'm using the exact same color as the one in designs, what do you mean? 🤔 

The grouped time entries have a different background colour on dark theme, look:
![image](https://user-images.githubusercontent.com/2173493/94684961-c37ea780-02f6-11eb-8aba-7198816d221d.png)

>> The tab indicator in the bottom nav

>~I will give one final try here and create an issue otherwise 👌~ Adressed :) 

👍 

>> The layout of the grouped time entries

>I'm also not sure what you mean here D:

They were supposed to look like this:
![image](https://user-images.githubusercontent.com/2173493/94684658-59660280-02f6-11eb-8d4b-d0ec8057ea9c.png)

The time entries in the middle of the group don't have rounded borders and the spacing is minimal.
I'm fine the way it is right now tbh.

This is what we have right now:
![image](https://user-images.githubusercontent.com/2173493/94684897-ad70e700-02f6-11eb-8db7-c43963b78050.png)

>> The grouped time entries swiping (not sure if we are doing, but it would be a nice detail to swipe the whole group) ¿¿

>We won't change them to swipe altogether until we are doing compose where this is much easier

👍

2020-09-30 12:35 UTC, daividssilverio approved these changes
Looking good to me.
The app crashes when switching tabs sometimes btw. 
`swipe_refresh_layout` is null. Using `viewLifecycleOwner.lifecycleScope` on `TimeEntryLogFragment:L146` would fix it.

Please create issues regarding confusion on designs (or we can discuss this internally only with our designers, up to you).

2020-09-30 12:39 UTC, merged