Fix push issues: batch 1
toggl/android pull request #951
Opened 2020-09-29 10:15 UTC by simonrozsival

## Info

### Summary
This PR fixes two bugs I found this morning. I know about more issues with updating TEs which I haven't finished debugging yet and which will be addressed later.

### Relationships
Closes #949, closes #950 

## Repository health

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

## Reviewing

### Pointers
Try it yourself in the emulator!

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

## Merge permissions
🦑

2020-09-29 12:24 UTC, heytherewill approved these changes

2020-09-29 12:25 UTC, heytherewill requested changes
Actually, please add a test to prevent us from making the null user mistake again

2020-09-29 21:49 UTC, daividssilverio commented on sync/src/test/java/com/toggl/sync/processing/ResponseProcessorTest.kt
> +        // if we reach the end of the test, no exception was thrown
There's this nice assertion that you could use here instead of leaving a comment
```
io.kotest.assertions.throwables.shouldNotThrowAny
```

2020-09-29 21:50 UTC, daividssilverio commented on sync/src/test/java/com/toggl/sync/processing/ResponseProcessorTest.kt
> +import io.mockk.mockk
```suggestion
import com.toggl.sync.BaseDatabaseTest
import io.kotest.assertions.throwables.shouldNotThrowAny
import io.mockk.mockk
```

2020-09-29 21:51 UTC, daividssilverio commented on sync/src/test/java/com/toggl/sync/processing/ResponseProcessorTest.kt
> +        // if we reach the end of the test, no exception was thrown
```suggestion
        shouldNotThrowAny {
            processor.process(response)
        }
```

2020-09-30 10:45 UTC, heytherewill approved these changes

2020-09-30 12:09 UTC, daividssilverio approved these changes

2020-09-30 13:23 UTC, merged